"""create candidates table

Revision ID: 2a6dbe385ed0
Revises: 
Create Date: 2025-04-16 22:19:03.141014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6dbe385ed0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('shift', sa.Enum('day', 'night', name='workshift'), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidates')
    # ### end Alembic commands ###
